# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "design_2_YOLO2_FPGA_0_0_synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.cache/wt [current_project]
set_property parent.project_path C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_CTRL_BUS_s_axi.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_DATA_BUS2_m_axi.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_DATA_BUS_m_axi.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_ama_addmuladd_6ns_1s_6s_6ns_6_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_beta_buffer.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_beta_tmp.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_clear_input_buffer.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_compute3.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_compute3_compute_buffer_0.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_compute3_compute_buffer_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_compute3_compute_buffer_23.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_copy_input_weight.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_copy_input_weight_weight_memcpy_buffer.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_load.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_load_RowBeginByte.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_load_input_memcpy_buffer.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_pixel_load.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_pixel_load_RowIntNum.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_input_pixel_load_RowOffset.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_intra_pingpong_wrapper.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_intra_pingpong_wrapper_input_buffer1_0.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_intra_pingpong_wrapper_weight_buffer1_0_0.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_10s_6ns_10ns_10_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_6ns_6ns_6ns_10_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_6ns_7ns_12ns_12_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_6ns_7ns_6ns_12_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_6ns_7ns_7ns_12_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mac_muladd_6ns_7ns_8ns_12_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_12ns_4ns_16_2_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_18ns_32s_32_5_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_2ns_12ns_14_2_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_2ns_14ns_16_2_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_2ns_2ns_4_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_31ns_34ns_65_5_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_32s_13ns_45_5_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_32s_32s_32_5_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_4s_4s_4_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_5ns_9ns_13_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_6ns_5ns_11_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_6ns_6ns_12_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_9ns_32s_32_5_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_9ns_9ns_18_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_mul_16s_16s_32_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_mul_18ns_11ns_29_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mul_mul_6ns_12ns_18_4_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mux_325_16_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_mux_325_32_1_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_output_buffer1_0.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_pool_yolo24.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_sdiv_32ns_32ns_32_36_seq_1.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_write_back_output_reorg.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA_write_back_output_reorg_output_tmp.v
  C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/imports/verilog/YOLO2_FPGA.v
}
read_ip -quiet c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.srcs/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cached_ip [config_ip_cache -export -no_bom  -dir C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1 -new_name design_2_YOLO2_FPGA_0_0 -ip [get_ips design_2_YOLO2_FPGA_0_0]]

OPTRACE "Configure IP Cache" END { }
if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_2_YOLO2_FPGA_0_0 -part xc7z020clg400-1 -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix design_2_YOLO2_FPGA_0_0_ design_2_YOLO2_FPGA_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_2_YOLO2_FPGA_0_0_stub.v
 lappend ipCachedFiles design_2_YOLO2_FPGA_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_2_YOLO2_FPGA_0_0_stub.vhdl
 lappend ipCachedFiles design_2_YOLO2_FPGA_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_2_YOLO2_FPGA_0_0_sim_netlist.v
 lappend ipCachedFiles design_2_YOLO2_FPGA_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_2_YOLO2_FPGA_0_0_sim_netlist.vhdl
 lappend ipCachedFiles design_2_YOLO2_FPGA_0_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp design_2_YOLO2_FPGA_0_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips design_2_YOLO2_FPGA_0_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all design_2_YOLO2_FPGA_0_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_YOLO2_FPGA_0_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "design_2_YOLO2_FPGA_0_0_synth_1_synth_report_utilization_0" "report_utilization -file design_2_YOLO2_FPGA_0_0_utilization_synth.rpt -pb design_2_YOLO2_FPGA_0_0_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0.dcp c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0.dcp c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0_stub.v c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0_stub.vhdl c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0_sim_netlist.v c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.runs/design_2_YOLO2_FPGA_0_0_synth_1/design_2_YOLO2_FPGA_0_0_sim_netlist.vhdl c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.ip_user_files/ip/design_2_YOLO2_FPGA_0_0]} {
  catch { 
    file copy -force c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.v C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.ip_user_files/ip/design_2_YOLO2_FPGA_0_0
  }
}

if {[file isdir C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.ip_user_files/ip/design_2_YOLO2_FPGA_0_0]} {
  catch { 
    file copy -force c:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.gen/sources_1/bd/design_2/ip/design_2_YOLO2_FPGA_0_0/design_2_YOLO2_FPGA_0_0_stub.vhdl C:/Users/abhij/OneDrive/Desktop/sem8/EE712/project/vivado/YOLO_FPGA/YOLO_FPGA.ip_user_files/ip/design_2_YOLO2_FPGA_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "design_2_YOLO2_FPGA_0_0_synth_1" END { }
